version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: ""
    update_schedule: "live"
    default_reviewers:
    - unasuke
    allowed_updates:
      - match:
          update_type: "all"
